# Generated by Django 3.2.16 on 2024-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241129_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts_image', verbose_name='Фото'),
        ),
    ]
